FROM node:20-alpine AS build
WORKDIR /app

COPY src/MiniLibrary.Web/package*.json ./
RUN npm ci

COPY src/MiniLibrary.Web/ .
RUN npm run build

FROM node:20-alpine AS runtime
WORKDIR /app
RUN npm install -g serve
COPY --from=build /app/dist ./dist
EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]
